// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

export function CreateSession(userID: number): Promise<model$0.Session | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3266597599, userID) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function DeleteSession(sessionID: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4043315358, sessionID) as any;
    return $resultPromise;
}

export function GetSession(sessionID: number): Promise<model$0.Session | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1324220753, sessionID) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function ValidateSession(sessionID: number): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2914261573, sessionID) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = model$0.Session.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
