// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export function DecodeLicense(key: string): Promise<model$0.License | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3265363978, key) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GenerateLicense(username: string, expiresAt: time$0.Time): Promise<model$0.License | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(748323289, username, expiresAt) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function ValidateLicense(key: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3062416526, key) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = model$0.License.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
