// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

export function Login(username: string, password: string): Promise<model$0.Session | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2837973582, username, password) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function Logout(sessionID: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2565517935, sessionID) as any;
    return $resultPromise;
}

export function RecoverPassword(username: string, answers: { [_: string]: string }, newPassword: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(178735934, username, answers, newPassword) as any;
    return $resultPromise;
}

export function Register(username: string, password: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(794949508, username, password) as any;
    return $resultPromise;
}

export function SetSecurityQuestions(username: string, questions: { [_: string]: string }): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2440743926, username, questions) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = model$0.Session.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
