name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Cache Go modules and Wails
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/wails
          key: ${{ runner.os }}-go-wails-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-go-wails-
            ${{ runner.os }}-go-

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v3/cmd/wails@latest
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run Go Tests
        run: go test -v ./...

      - name: Build Wails Application
        run: wails3 build